### ISSUE TITLE
http://www.snik.eu/ontology/ob/Vendor

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#302] opened 2019-04-18 13:37 UTC
The class http://www.snik.eu/ontology/ob/Vendor has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
muss Rolle sein. Bitte Umgebung prüfen.

**Comment by AnnaLoerke** [comment] 2019-04-23 12:40
Duplicate of #288

**Closed by AnnaLoerke** 2019-04-23 12:40 UTC
Labels: duplicate
